# Generated by Django 5.2.17 on 2026-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autore', models.CharField(help_text='Come compare sul canale di origine. Anche solo nome e iniziale.', max_length=80, verbose_name='nome')),
                ('voce', models.CharField(choices=[('owner', 'Proprietario'), ('guest', 'Ospite')], default='guest', max_length=10, verbose_name='chi parla')),
                ('testo', models.TextField(help_text="Riportato fedelmente. Si puo' accorciare, non riscrivere.", verbose_name='testo')),
                ('canale', models.CharField(help_text="Dove e' stata pubblicata: Airbnb, Booking.com, Google, email…", max_length=60, verbose_name='canale')),
                ('data', models.DateField(verbose_name='data')),
                ('url', models.URLField(blank=True, help_text="Alla recensione originale, se e' pubblica. Rende verificabile ciò che si afferma.", verbose_name='collegamento')),
                ('luogo', models.CharField(blank=True, help_text="Facoltativo: l'immobile o la zona a cui si riferisce.", max_length=100, verbose_name='località')),
                ('in_evidenza', models.BooleanField(default=True, help_text='Se disattivata, resta in archivio ma non compare in home.', verbose_name='in evidenza')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='ordine')),
            ],
            options={
                'verbose_name': 'recensione',
                'verbose_name_plural': 'recensioni',
                'ordering': ['ordine', '-data'],
            },
        ),
    ]
