# Generated by Django 5.2.17 on 2026-09-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='canale',
            field=models.CharField(help_text='Dove è stata pubblicata: Airbnb, Booking.com, Google, email…', max_length=60, verbose_name='canale'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='url',
            field=models.URLField(blank=True, help_text='Alla recensione originale, se è pubblica. Rende verificabile ciò che si afferma.', verbose_name='collegamento'),
        ),
    ]
