# Generated by Django 5.2.17 on 2026-09-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('categoria', models.CharField(choices=[('proprietari', 'Per i proprietari'), ('localita', 'Località'), ('ospiti', 'Consigli per ospiti'), ('novita', 'Novità')], db_index=True, default='novita', help_text='Compare come occhiello sopra il titolo e nella barra dei filtri.', max_length=20, verbose_name='Categoria')),
                ('estratto', models.TextField(help_text="Due righe. Si leggono nell'elenco e nei risultati di ricerca.", max_length=400, verbose_name='Estratto')),
                ('sottotitolo', models.CharField(blank=True, help_text="Facoltativo: la frase sotto il titolo nella pagina dell'articolo.", max_length=300, verbose_name='Sottotitolo')),
                ('corpo', models.TextField(help_text='Paragrafi separati da una riga vuota. Una riga che comincia per «## » diventa un sottotitolo.', verbose_name='Corpo')),
                ('citazione', models.TextField(blank=True, help_text="Facoltativa: compare a meta' articolo, in corsivo.", verbose_name='Citazione')),
                ('citazione_fonte', models.CharField(blank=True, max_length=160, verbose_name='Fonte della citazione')),
                ('copertina', models.ImageField(blank=True, upload_to='giornale/%Y/%m/', verbose_name='Copertina')),
                ('copertina_alt', models.CharField(blank=True, max_length=200, verbose_name='Testo alternativo della copertina')),
                ('pubblicato_il', models.DateField(db_index=True, verbose_name='Data di pubblicazione')),
                ('tempo_lettura', models.PositiveIntegerField(default=0, help_text='Lasciare a zero: viene calcolato dal corpo alla prima salvata.', verbose_name='Tempo di lettura (minuti)')),
                ('autore', models.CharField(default='Redazione EV House', max_length=120, verbose_name='Firma')),
                ('tag', models.CharField(blank=True, help_text='Separati da virgola. Sono etichette da leggere, non filtri: a filtrare ci pensa la categoria.', max_length=250, verbose_name='Tag')),
                ('mostra_stagione', models.BooleanField(default=False, help_text='Aggiunge la fascia con occupazione, notti e immobili gestiti. I valori sono quelli di settings.py, gli stessi della home: non vanno riscritti qui, altrimenti un giorno divergono.', verbose_name='Mostra i numeri della stagione')),
                ('in_evidenza', models.BooleanField(default=False, help_text="Il piu' recente fra quelli in evidenza apre l'elenco.", verbose_name='In evidenza')),
                ('pubblicato', models.BooleanField(default=False, help_text='Solo gli articoli pubblicati compaiono sul sito e in sitemap.', verbose_name='Pubblicato')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('creato_il', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('aggiornato_il', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['-pubblicato_il', '-id'],
                'indexes': [models.Index(fields=['pubblicato', '-pubblicato_il'], name='blog_articl_pubblic_e1b171_idx')],
            },
        ),
    ]
