# Generated by Django 5.2.17 on 2026-09-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articoli_iniziali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='in_evidenza',
            field=models.BooleanField(default=False, help_text="Il più recente fra quelli in evidenza apre l'elenco.", verbose_name='In evidenza'),
        ),
    ]
