# Generated by Django 5.2.17 on 2026-08-19 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('location', models.CharField(max_length=200, verbose_name='Localita')),
                ('short_description', models.TextField(max_length=400, verbose_name='Descrizione breve')),
                ('description', models.TextField(verbose_name='Descrizione completa')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Camere da letto')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Bagni')),
                ('guests', models.PositiveIntegerField(default=2, verbose_name='Ospiti')),
                ('featured', models.BooleanField(default=False, verbose_name='In evidenza')),
                ('booking_url', models.URLField(blank=True, verbose_name='URL prenotazione')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
            ],
            options={
                'verbose_name': 'Immobile',
                'verbose_name_plural': 'Immobili',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/', verbose_name='Immagine')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Testo alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Immobile')),
            ],
            options={
                'verbose_name': 'Immagine immobile',
                'verbose_name_plural': 'Immagini immobile',
                'ordering': ['order', 'id'],
            },
        ),
    ]
