# Generated by Django 5.2.17 on 2026-08-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Dotazione',
                'verbose_name_plural': 'Dotazioni',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-featured', 'title'], 'verbose_name': 'Immobile', 'verbose_name_plural': 'Immobili'},
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Indirizzo'),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('Appartamento', 'Appartamento'), ('Aparthotel', 'Aparthotel'), ('Villa', 'Villa'), ('Hotel', 'Hotel')], max_length=32, verbose_name='Tipologia'),
        ),
        migrations.AddField(
            model_name='property',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='ID sul portale'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitudine'),
        ),
        migrations.AddField(
            model_name='property',
            name='license_code',
            field=models.CharField(blank=True, help_text='Codice identificativo obbligatorio per le locazioni brevi.', max_length=60, verbose_name='Codice licenza'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitudine'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('published', 'Pubblicato'), ('draft', 'Bozza')], default='draft', help_text='Solo gli immobili pubblicati compaiono sul sito e nella sitemap.', max_length=12, verbose_name='Stato'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Nome del file sul portale: evita di riscaricare la stessa foto.', max_length=120, verbose_name='Riferimento originale'),
        ),
        migrations.AlterField(
            model_name='property',
            name='booking_url',
            field=models.URLField(blank=True, help_text='Scheda sul portale esterno: da lì passano disponibilità e tariffe.', verbose_name='URL prenotazione'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrizione completa'),
        ),
        migrations.AlterField(
            model_name='property',
            name='short_description',
            field=models.TextField(blank=True, max_length=400, verbose_name='Descrizione breve'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity', verbose_name='Dotazioni'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'location'], name='properties__status_4b45e5_idx'),
        ),
    ]
