# Generated by Django 5.2.17 on 2026-09-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_amenity_alter_property_options_property_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['-copertina', 'order', 'id'], 'verbose_name': 'Immagine immobile', 'verbose_name_plural': 'Immagini immobile'},
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='copertina',
            field=models.BooleanField(default=False, help_text="La foto che apre l'immobile ovunque: scheda, pagina, galleria e anteprima social. Una sola per immobile: spuntandone un'altra, la precedente si libera da se'. Senza nessuna spunta vale la prima del portale.", verbose_name='Copertina'),
        ),
    ]
