# Generated by Django 5.2.17 on 2026-09-08 09:18

from django.db import migrations, models


def allinea_ai_valori_attuali(apps, schema_editor):
    """Quel che c'e' oggi e' quel che ha dato il portale: si registra com'e'.

    Serve perche' la guardia dell'importatore confronta il valore attuale con
    l'ultimo arrivato dal portale. Senza questo allineamento le righe gia' in
    banca dati partirebbero col campo vuoto, cioe' senza niente da proteggere.
    """
    Property = apps.get_model("properties", "Property")
    for immobile in Property.objects.all():
        Property.objects.filter(pk=immobile.pk).update(
            valori_portale={"title": immobile.title, "category": immobile.category}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertyimage_options_propertyimage_copertina'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='valori_portale',
            field=models.JSONField(blank=True, default=dict, help_text="Ultimo valore arrivato dal portale per i campi riscrivibili. Dove il valore qui sopra e' diverso, il campo e' stato riscritto a mano e l'importazione non lo tocca piu'.", verbose_name='Valori dal portale'),
        ),
        migrations.RunPython(allinea_ai_valori_attuali, migrations.RunPython.noop),
    ]
