# Generated by Django 5.2.17 on 2026-09-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_valori_dal_portale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='valori_portale',
            field=models.JSONField(blank=True, default=dict, help_text="Ultimo valore arrivato dal portale per i campi riscrivibili. Dove il valore qui sopra è diverso, il campo è stato riscritto a mano e l'importazione non lo tocca più.", verbose_name='Valori dal portale'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='copertina',
            field=models.BooleanField(default=False, help_text="La foto che apre l'immobile ovunque: scheda, pagina, galleria e anteprima social. Una sola per immobile: spuntandone un'altra, la precedente si libera da sé. Senza nessuna spunta vale la prima del portale.", verbose_name='Copertina'),
        ),
    ]
